# Generated by Django 2.0.2 on 2018-03-30 03:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paste_name', models.CharField(max_length=200)),
                ('type_content_paste', models.CharField(max_length=200)),
                ('content_paste', models.TextField()),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_end', models.DateTimeField()),
                ('is_private', models.BooleanField(default=0)),
                ('short_link', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('nick_name', models.CharField(max_length=200)),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_end', models.DateTimeField()),
                ('role_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userzone.Role')),
            ],
        ),
        migrations.AddField(
            model_name='paste',
            name='user_own',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userzone.User'),
        ),
    ]
