# Generated by Django 2.0.2 on 2018-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userzone', '0005_auto_20180331_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_user',
        ),
        migrations.AlterField(
            model_name='paste',
            name='user_own',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
